const title = document.querySelector(`.title`);
const post = document.querySelector(`.post`);
console.log(title);
console.log(post);

const pageContent = [
  {
    title: `Sadio Mane on brink of £34.6m Bayern Munich transfer after agreeing personal terms`,
    body: `Sadio Mane has agreed personal terms with Bayern Munich over a three-year deal at the club, with the Germans closing in on a £34.6million move for the Senegal winger.. Suspendisse commodo leo nec ornare posuere. Suspendisse quis est non sem feugiat maximus eget ut ante. Aenean fermentum ipsum libero, sit amet laoreet leo mattis vel. Praesent magna tortor, interdum vitae neque a, feugiat porta purus. In sagittis ultricies eros ut elementum. Duis suscipit neque quis quam eleifend facilisis. Proin ut est euismod ipsum laoreet auctor quis et justo. Aliquam dictum euismod velit, sagittis dignissim odio. Duis eget velit eget purus imperdiet sollicitudin. Suspendisse varius libero ligula, eu sagittis sapien lacinia scelerisque. Nullam odio nisl, sagittis vel condimentum pellentesque, laoreet eu nibh. Maecenas blandit mauris et commodo egestas. Aenean mattis congue est, vel facilisis odio lacinia et. Suspendisse a purus dolor. Morbi vitae nibh sit amet lectus molestie blandit iaculis et est. Aenean pharetra mauris sit amet ex ornare, ut euismod nibh tincidunt. Donec ullamcorper finibus suscipit. Curabitur tempor urna quis turpis tempor pellentesque. Fusce placerat ac sem et vehicula. Sed fringilla sem fermentum libero consequat ornare. Etiam dictum purus nec diam tincidunt facilisis. Proin a convallis nibh, et molestie tortor. Integer tempus aliquam sodales. Pellentesque luctus, libero sit amet ultrices porta, nibh purus finibus turpis, at ullamcorper mi dolor eget neque. `,
  },
  {
    title: `Nipsey Hussle's Last Moments Detailed As Murder Trial Opens`,
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis orci sapien. Suspendisse commodo leo nec ornare posuere. Suspendisse quis est non sem feugiat maximus eget ut ante. Aenean fermentum ipsum libero, sit amet laoreet leo mattis vel. Praesent magna tortor, interdum vitae neque a, feugiat porta purus. In sagittis ultricies eros ut elementum. Duis suscipit neque quis quam eleifend facilisis. Proin ut est euismod ipsum laoreet auctor quis et justo. Aliquam dictum euismod velit, sagittis dignissim odio. Duis eget velit eget purus imperdiet sollicitudin. Suspendisse varius libero ligula, eu sagittis sapien lacinia scelerisque. Nullam odio nisl, sagittis vel condimentum pellentesque, laoreet eu nibh. Maecenas blandit mauris et commodo egestas. Aenean mattis congue est, vel facilisis odio lacinia et. Suspendisse a purus dolor. Morbi vitae nibh sit amet lectus molestie blandit iaculis et est. Aenean pharetra mauris sit amet ex ornare, ut euismod nibh tincidunt. Donec ullamcorper finibus suscipit. Curabitur tempor urna quis turpis tempor pellentesque. Fusce placerat ac sem et vehicula. Sed fringilla sem fermentum libero consequat ornare. Etiam dictum purus nec diam tincidunt facilisis. Proin a convallis nibh, et molestie tortor. Integer tempus aliquam sodales. Pellentesque luctus, libero sit amet ultrices porta, nibh purus finibus turpis, at ullamcorper mi dolor eget neque. `,
  },
  {
    title: `"Sapa dey follow this guy" - Reactions as netizens discover what Twitter influencer, Daniel Regha does for a living (Video)`,
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis orci sapien. Suspendisse commodo leo nec ornare posuere. Suspendisse quis est non sem feugiat maximus eget ut ante. Aenean fermentum ipsum libero, sit amet laoreet leo mattis vel. Praesent magna tortor, interdum vitae neque a, feugiat porta purus. In sagittis ultricies eros ut elementum. Duis suscipit neque quis quam eleifend facilisis. Proin ut est euismod ipsum laoreet auctor quis et justo. Aliquam dictum euismod velit, sagittis dignissim odio. Duis eget velit eget purus imperdiet sollicitudin. Suspendisse varius libero ligula, eu sagittis sapien lacinia scelerisque. Nullam odio nisl, sagittis vel condimentum pellentesque, laoreet eu nibh. Maecenas blandit mauris et commodo egestas. Aenean mattis congue est, vel facilisis odio lacinia et. Suspendisse a purus dolor. Morbi vitae nibh sit amet lectus molestie blandit iaculis et est. Aenean pharetra mauris sit amet ex ornare, ut euismod nibh tincidunt. Donec ullamcorper finibus suscipit. Curabitur tempor urna quis turpis tempor pellentesque. Fusce placerat ac sem et vehicula. Sed fringilla sem fermentum libero consequat ornare. Etiam dictum purus nec diam tincidunt facilisis. Proin a convallis nibh, et molestie tortor. Integer tempus aliquam sodales. Pellentesque luctus, libero sit amet ultrices porta, nibh purus finibus turpis, at ullamcorper mi dolor eget neque. `,
  },
  {
    title: `How to register for your PVC online in 5 simple steps`,
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis orci sapien. Suspendisse commodo leo nec ornare posuere. Suspendisse quis est non sem feugiat maximus eget ut ante. Aenean fermentum ipsum libero, sit amet laoreet leo mattis vel. Praesent magna tortor, interdum vitae neque a, feugiat porta purus. In sagittis ultricies eros ut elementum. Duis suscipit neque quis quam eleifend facilisis. Proin ut est euismod ipsum laoreet auctor quis et justo. Aliquam dictum euismod velit, sagittis dignissim odio. Duis eget velit eget purus imperdiet sollicitudin. Suspendisse varius libero ligula, eu sagittis sapien lacinia scelerisque. Nullam odio nisl, sagittis vel condimentum pellentesque, laoreet eu nibh. Maecenas blandit mauris et commodo egestas. Aenean mattis congue est, vel facilisis odio lacinia et. Suspendisse a purus dolor. Morbi vitae nibh sit amet lectus molestie blandit iaculis et est. Aenean pharetra mauris sit amet ex ornare, ut euismod nibh tincidunt. Donec ullamcorper finibus suscipit. Curabitur tempor urna quis turpis tempor pellentesque. Fusce placerat ac sem et vehicula. Sed fringilla sem fermentum libero consequat ornare. Etiam dictum purus nec diam tincidunt facilisis. Proin a convallis nibh, et molestie tortor. Integer tempus aliquam sodales. Pellentesque luctus, libero sit amet ultrices porta, nibh purus finibus turpis, at ullamcorper mi dolor eget neque. `,
  },
  {
    title: `ASUU strike: A lot is going on behind the scenes - FG`,
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent quis orci sapien. Suspendisse commodo leo nec ornare posuere. Suspendisse quis est non sem feugiat maximus eget ut ante. Aenean fermentum ipsum libero, sit amet laoreet leo mattis vel. Praesent magna tortor, interdum vitae neque a, feugiat porta purus. In sagittis ultricies eros ut elementum. Duis suscipit neque quis quam eleifend facilisis. Proin ut est euismod ipsum laoreet auctor quis et justo. Aliquam dictum euismod velit, sagittis dignissim odio. Duis eget velit eget purus imperdiet sollicitudin. Suspendisse varius libero ligula, eu sagittis sapien lacinia scelerisque. Nullam odio nisl, sagittis vel condimentum pellentesque, laoreet eu nibh. Maecenas blandit mauris et commodo egestas. Aenean mattis congue est, vel facilisis odio lacinia et. Suspendisse a purus dolor. Morbi vitae nibh sit amet lectus molestie blandit iaculis et est. Aenean pharetra mauris sit amet ex ornare, ut euismod nibh tincidunt. Donec ullamcorper finibus suscipit. Curabitur tempor urna quis turpis tempor pellentesque. Fusce placerat ac sem et vehicula. Sed fringilla sem fermentum libero consequat ornare. Etiam dictum purus nec diam tincidunt facilisis. Proin a convallis nibh, et molestie tortor. Integer tempus aliquam sodales. Pellentesque luctus, libero sit amet ultrices porta, nibh purus finibus turpis, at ullamcorper mi dolor eget neque. `,
  },
];

window.addEventListener(`load`, () => {
  title.innerHTML = pageContent[getRandomNumber()].title;
});
function getRandomNumber() {
  return Math.floor(Math.random() * pageContent.length);
}
